// <auto-generated />
namespace UsersCrudMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migration_filename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_filename));
        
        string IMigrationMetadata.Id
        {
            get { return "201808260532233_migration_filename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
